
---
# Source: kubedb-crd-installer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedb-crd-installer
  namespace: default
  labels:
    helm.sh/chart: kubedb-crd-installer-0.1.0
    app.kubernetes.io/name: kubedb-crd-installer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install,pre-install,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
---
# Source: kubedb-crd-installer/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedb-crd-installer
  labels:
    helm.sh/chart: kubedb-crd-installer-0.1.0
    app.kubernetes.io/name: kubedb-crd-installer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install,pre-install,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - kubedb.com
  - catalog.kubedb.com
  - appcatalog.appscode.com
  resources:
  - "*"
  verbs: ["get", "list"]
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs: ["delete"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs: ["delete"]
---
# Source: kubedb-crd-installer/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedb-crd-installer
  labels:
    helm.sh/chart: kubedb-crd-installer-0.1.0
    app.kubernetes.io/name: kubedb-crd-installer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedb-crd-installer
subjects:
- kind: ServiceAccount
  name: kubedb-crd-installer
  namespace: default
---
# Source: kubedb-crd-installer/templates/installer.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kubedb-crd-installer-installer
  namespace: default
  labels:
    helm.sh/chart: kubedb-crd-installer-0.1.0
    app.kubernetes.io/name: kubedb-crd-installer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install,pre-install,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
spec:
  backoffLimit: 3
  # activeDeadlineSeconds: 300
  # ttlSecondsAfterFinished: 10
  template:
    spec:
      serviceAccountName: kubedb-crd-installer
      containers:
      - name: installer
        image: tigerworks/helm-crd-fixer:latest
        imagePullPolicy: Always
      # containers:
      # - name: cleaner
      #   image: appscode/kubectl:1.22
      #   command:
      #     - sh
      #     - -c
      #     - "sleep 2; \
      #        kubectl delete clusterrole kubedb-crd-installer || true; \
      #        kubectl delete clusterrolebinding kubedb-crd-installer || true; \
      #        sleep 2; \
      #        kubectl delete serviceaccount kubedb-crd-installer || true;"
      #   imagePullPolicy: Always
      restartPolicy: Never
