apiVersion: v1
kind: Pod
metadata:
  name: installer
  labels:
    app: installer
spec:
  containers:
  - image: tigerworks/helm-crd-fixer:latest
    imagePullPolicy: IfNotPresent
    name: installer
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  restartPolicy: Always
