apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubedb-crd-installer.fullname" . }}
  labels:
    {{- include "kubedb-crd-installer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-install,pre-rollback
    # "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - kubedb.com
  - catalog.kubedb.com
  resources:
  - "*"
  verbs: ["*"]
