apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubedb-crd-installer.fullname" . }}-installer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedb-crd-installer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-install,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 10
  template:
    spec:
      serviceAccountName: {{ include "kubedb-crd-installer.serviceAccountName" . }}
      containers:
      - name: installer
        image: tigerworks/helm-crd-fixer:v0.19.0
        imagePullPolicy: Always
      # containers:
      # - name: cleaner
      #   image: appscode/kubectl:1.22
      #   command:
      #     - sh
      #     - -c
      #     - "sleep 2; \
      #        kubectl delete clusterrole {{ include "kubedb-crd-installer.fullname" . }} || true; \
      #        kubectl delete clusterrolebinding {{ include "kubedb-crd-installer.fullname" . }} || true; \
      #        sleep 2; \
      #        kubectl delete serviceaccount {{ include "kubedb-crd-installer.serviceAccountName" . }} || true;"
      #   imagePullPolicy: Always
      restartPolicy: Never
