apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubedb-crd-installer.fullname" . }}-installer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedb-crd-installer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-install,pre-rollback
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    spec:
      serviceAccountName: {{ include "kubedb-crd-installer.serviceAccountName" . }}
      containers:
      - name: installer
        image: tigerworks/helm-crd-fixer:latest
        imagePullPolicy: Always
      restartPolicy: Never
