apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubedb-crd-installer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedb-crd-installer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-install,pre-rollback
    # "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
