apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubedb-crd-installer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedb-crd-installer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
